repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .*\.tsv|.*\.md
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
        args:
          - "--maxkb=10000"
      - id: no-commit-to-branch
        args:
          - "--branch=master"
      - id: debug-statements
      - id: name-tests-test

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/config-conventional@v19.8.1"

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: just code-lint
        language: system
        types: [file]
        files: \.(js|ts|jsx|tsx)$
        pass_filenames: false

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: just code-format
        language: system
        types: [file]
        files: \.(js|ts|jsx|tsx|css|md|json|yaml)$
        pass_filenames: false

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.13.3
    hooks:
      - id: cspell

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
        args:
          - "--dialect=postgres"
      - id: sqlfluff-fix
        args:
          - "--dialect=postgres"

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.94.1
    hooks:
      - id: terraform_fmt
