export default {
  files: ["**", ".*/**"],
  ignorePaths: [
    ".git",
    ".gitignore",
    ".github",
    ".pre-commit-config.yaml",
    ".secrets.baseline",
    "justfile",
    "CHANGELOG.md",
    "node_modules",
    "package.json",
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "next.config.ts",
    "terraform",
    "supabase",
    "src/components/ascii-donut.tsx",
  ],
  words: [
    "workdir",
    "tseslint",
    "jsxa",
    "espree",
    "Gleb",
    "Khaykin",
    "khaykingleb",
    "daisyui",
    "conventionalcommits",
    "vercel",
    "katex",
    "pageid",
    "changefreq",
    "doesn",
    "supabase",
    "jsonencode",
    "signup",
    "architecting",
    "PGRST",
    "prefersdark",
    "nums",
    "Karpenter",
    "dotenv",
    "migra",
    "ngrok",
    "justfile",
  ],
};
